### ISSUE TITLE
Problem about "RuntimeError: CUDA out of memory."

### ISSUE THREAD

**Issue by CodingCatMountain** [robotflow-initiative/dipgrasp#4]
@SJTUzjy @YoruCathy @ElectronicElephant @dwxrycb123 @Spphire Hi, My GPU is NIVIDA 4060. I have 8GiB memory. However, When I run the ``main.py``, I met such problem:
```
base_link No collision mesh here!
left_hand_d No collision mesh here!
left_hand_h No collision mesh here!
left_hand_d2 No collision mesh here!
left_hand_e3 No collision mesh here!
left_hand_e No collision mesh here!
left_hand_e4 No collision mesh here!
left_hand_e5 No collision mesh here!
left_hand_virtual_a No collision mesh here!
  0%|                                                                                                                                                                      | 0/8 [00:00<?, ?it/s]
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/wjj/mdisk/dipgrasp/main.py", line 127, in main
    poses, joints = generate_grasp_for_obj(ptCloud, gripper, algo_cfg)
  File "/home/wjj/mdisk/dipgrasp/main.py", line 74, in generate_grasp_for_obj
    final_pose, final_joint = dipgrasp(src_points_,
  File "/home/wjj/mdisk/dipgrasp/core/dipgrasp.py", line 94, in dipgrasp
    pair_map = match_nearest_points(src_points, src_normals, cfg)
  File "/home/wjj/mdisk/dipgrasp/core/geometry/matchNearestPoints.py", line 19, in match_nearest_points
    d = d_1 + d_2 - 2 * d_3
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.95 GiB. GPU 0 has a total capacity of 7.75 GiB of which 1.50 GiB is free. Including non-PyTorch memory, this process has 6.02 GiB memory in use. Of the allocated memory 5.89 GiB is allocated by PyTorch, and 26.67 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

```
Could You help me solve this problem?

**Comment by ElectronicElephant** [comment]
Hi Jiajun,

You can try to tune `total_num` lower and see if it fits into your GPU memory.

**Comment by SJTUzjy** [comment]
Hi, CodingCatMountain.
To resolve this issue, you need to adjust the algo_params.sample_time parameter in the conf/default.yaml file. You can either modify the yaml file directly or simply update the command line
`python main.py`
into
`python main.py algo_params.sample_time=64`
to set the grasp trial number as 64.

**Comment by CodingCatMountain** [comment]
![dipgrasp](https://github.com/user-attachments/assets/de12fcae-e650-491a-b6e0-5e8a9852cb47)
@SJTUzjy @YoruCathy @ElectronicElephant @dwxrycb123 Thanks, it can output some results.

**Comment by CodingCatMountain** [comment]
I will close this issue. But I want to open another issue to discuss the robotic dexterous hand grasping with you guys since I am a greenhand in this field, I study manipulator imitation learning before, but new I was assigned to study this field : |  . So If possibly could I ask you for email address or wechat (weixin) or another way of contact？

**Comment by SJTUzjy** [comment]
Please refer to our paper where you could find the authors’ email address.
