### ISSUE TITLE
Something Wrong with xml generator

### ISSUE THREAD

**Issue by matthewmzy** [robotflow-initiative/dipgrasp#5]
Thanks for your awesome work and having effienctly solved my last issue. But now I met a new one.
xml file in your dataset is too sparse for my use, so I want to generate more dense point clout for my palmar side of shadow hand. But when I run PointCloud.x86_64, and load my urdf into the unity engine, I just saw a stuff drop rapidly from some distace away. And perhaps it splited into several pieces. While run on windows is ok, but not perfect. As the picture shows, some link seemed to be ignored and points distributes unevenly. Do you know why?
![Uploading Screenshot 2024-10-15 162239.png…]()

**Comment by SJTUzjy** [comment]
Hi matthewmzy,
For the OS issue, please remove the path\to\xml_from_URDF_Linux\PointCloud_Data\Plugins\libdl.so, just like we have done with your previous issue.
Regarding your second problem, I am not able to see the picture you uploaded. However, it sounds like the difference between the collision mesh and visual mesh in your shadow URDF might be causing the odd visualization results. Could you try re-uploading the image, or provide more details so we can better assist you?

**Comment by matthewmzy** [comment]
<img width="946" alt="shot" src="https://github.com/user-attachments/assets/a5b8cfe7-cc2e-43a2-ad71-ae767470c5d5">
Can you see the picture now? So simply set all my collision mesh to visual will solve it, right?
