### ISSUE TITLE
Sometimes the app ''PointCloud.x86_64" could not load the dexterous hand...

### ISSUE THREAD

**Issue by CodingCatMountain** [robotflow-initiative/dipgrasp#9]
Hi, @davidliyutong @dwxrycb123 @SJTUzjy   I found some strange properties of ''PointCloud.x86_64". First of all, this app could not load another 3d format, e.g., ``.obj``, except for ``dae`` files.. 
However, I get confused.  
I use the ``ability_hand`` urdf from [this repo](https://github.com/dexsuite/dex-urdf). And I converted ``obj`` file into ``dae`` file. Beside, I can use ``urdfpy`` to visual my hand model. As you can see in below:
![2024-11-07_14-02](https://github.com/user-attachments/assets/0a15ac18-7bbb-47e3-a88e-964ce40046b5)

But I cannot visual the hand model in ``PointCloud.x86_64``.

Below is the modified ability_hand urdf file, which I modified from the open-source urdf file: 
[ability_hand_left.zip](https://github.com/user-attachments/files/17656772/ability_hand_left.zip)

Could you tell me are there any another trick to use ``PointCloud.x86_64``?

**Comment by CodingCatMountain** [comment]
@SJTUzjy  @davidliyutong @dwxrycb123 I got another problem here. I use the original urdf file of ability-hand from [this repo](https://github.com/psyonicinc/ability-hand-api). I can successfully show the ability-hand, however, I can't generate the point cloud of ability-hand.
![2024-11-07_17-17](https://github.com/user-attachments/assets/64346564-ae67-4c46-be3f-5ce6309218c6)

I can also attach the urdf file here. 
[ability_hand.zip](https://github.com/user-attachments/files/17659156/ability_hand.zip)


Looking forward to your reply. 
Sincerely, Kacun.

**Comment by ElectronicElephant** [comment]
Would you please kindly stop @ mentioning so many people at the same time? It's really impolite and annoying.

**Comment by CodingCatMountain** [comment]
@ElectronicElephant Sorry for @ the wrong person.

**Comment by CodingCatMountain** [comment]
> Would you please kindly stop @ mentioning so many unrelated people at the same time? It's really impolite and annoying. @CodingCatMountain @CodingCatMountain @CodingCatMountain

sorry for @ the wrong person. I don't know why the github automatically pop out your ID. My bad.

**Comment by CodingCatMountain** [comment]
Ok, I know why this problem will happen... Each link should have collision tag. I will close this issue.
